version: 2.1

jobs:
  build:
    docker:
      - image: node:10-alpine

    steps:
      - checkout
      - run:
          name: Install Node deps
          command: npm install
      - run:
          name: Build app
          command: npm run lint

  test:
    docker:
      - image: node:10-alpine

    steps:
      - checkout
      - run:
          name: Install Node deps
          command: npm install
      - run:
          name: Test app
          command: npm run test
  # analyze:
  analyze:
    docker:
      - image: node:10-alpine

    steps:
      - checkout
      - run:
          name: Install Node deps
          command: npm install
      - run:
          name: Audit app
          command: npm audit

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
