version: 2.1
jobs:
  build:
    docker:
      - image: "node:10-alpine"
  steps:
    - checkout
    - run: null
      name: Install Node Deps
      command: npm install
workflows:
  default:
    jobs:
      - build
