version: 2.1
jobs:
  build:
  docker:
    - image: node:10-alpine

  steps:
    - checkout
    - run:
      name: Install Node Deps
      command: npm install
# test :

#analyze:

workflows:
  default:
    jobs:
      - build
    # -test:
    #   requires:
    #   - build
    # -analyze:
    #   requires:
    #   - test
